### ISSUE TITLE
Метод containsGame не видит последнюю добавленную игру в каталог

### ISSUE THREAD

**Issue by Ntetikova** [Ntetikova/DiplomTeamWork_java#1]
# Описание
Проверяя наличие игр, последняя из добавленных игр в каталог не попадает, метод containsGame возвращает false.
# Локация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/694beef00cedd12fa2c93db300d36a03f84783dc/src/main/java/ru/netology/GameStore.java#L33
# Шаги Воспроизведения
1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
2. Воспроизвести тест shouldAddMoreGames
3. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит, все добавленные игры находит
**Фактический результат:** тест не проходит, последняя игра из каталога не находится

# Скриншот
![image](https://user-images.githubusercontent.com/121807872/227264987-b6de863e-3449-47d0-861f-15b62124d06e.png)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **JAVA:** OpenJDK 11

**Comment by OlgaMelman** [comment]
код исправлен. тест проходит
![addgames](https://user-images.githubusercontent.com/107468964/228544822-6743f008-489b-4f77-8fb7-8750ab497b44.png)
