### ISSUE TITLE
Метод publishGame разрешает добавить в каталог одинаковые игры.

### ISSUE THREAD

**Issue by Ntetikova** [Ntetikova/DiplomTeamWork_java#2]
# Описание
Метод publishGame перед добавлением новых игр в каталог не делает проверку на наличие одинаковых игр с одинаковым названием и жанром и разрешает их добавить в каталог.

# Локация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/694beef00cedd12fa2c93db300d36a03f84783dc/src/main/java/ru/netology/GameStore.java#L22

# Шаги Воспроизведения
1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
2. Воспроизвести тест shouldNotAddSameGames
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит, одинаковые игры не добавляются
*Фактический результат:* тест не проходит, одинаковые игры добавляются

# Скриншот
![image](https://user-images.githubusercontent.com/121807872/227275146-e0a80588-8f0c-4b80-b3f7-12afa39f7842.png)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **JAVA:** OpenJDK 11

**Comment by OlgaMelman** [comment]
код исправлен, тест проходит
![notsame](https://user-images.githubusercontent.com/107468964/228580761-450209d3-e651-4226-9ead-262de483a117.png)
