### ISSUE TITLE
Не суммирует время игрока, которое он провёл в игре.

### ISSUE THREAD

**Issue by Ntetikova** [Ntetikova/DiplomTeamWork_java#3]
# Описание
В методе getSumPlayedTime всегда возвращается изначальное значение времени, заданное при установке игры - 0.

# Локализация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/694beef00cedd12fa2c93db300d36a03f84783dc/src/main/java/ru/netology/GameStore.java#L76

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
2. Запустить тест shouldSumPlayedTime

**Ожидаемый результат:** тест пройден, сумма времени, проведённой в игре равна 10.
**Фактический результат:** тест провален, сумма времени, проведенного в игре 0.

# Скриншот
![image](https://user-images.githubusercontent.com/121807872/227285749-c4f1d5a4-ac32-4c02-ab13-c78a89162a18.png)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **JAVA:** OpenJDK 11

**Comment by OlgaMelman** [comment]
Код исправлен в 2-х методах: getSumPlayedTime и addPlayTime
При исправлении метода getSumPlayedTime - тест снова заваливался.
При изменении входных данных на 2 разные игры - тест проходит (необходимо дописать этот тест.)

# Скриншот измененного теста
![Screenshot_1](https://user-images.githubusercontent.com/107468964/228596919-5afd1de4-d8da-47e4-b7c9-a000623e910e.png)


# Локация дефекта 
https://github.com/Ntetikova/DiplomTeamWork_java/blob/694beef00cedd12fa2c93db300d36a03f84783dc/src/main/java/ru/netology/GameStore.java#L48

# Скриншот 
![2](https://user-images.githubusercontent.com/107468964/228601441-39793475-fed8-419a-8ab2-3134fa02cc36.png)
