### ISSUE TITLE
Метод getMostPlayer не возвращает имя игрока, если в игрe он играл не более часа

### ISSUE THREAD

**Issue by Ntetikova** [Ntetikova/DiplomTeamWork_java#4]
# Описание
Метод getMostPlayer возвращает null, если игроки играли в игры не более одного часа.

# Локация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/694beef00cedd12fa2c93db300d36a03f84783dc/src/main/java/ru/netology/GameStore.java#L59

# Шаги Воспроизведения
1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
2. Воспроизвести тест testGetMostPlayerInOneHour
3. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит
**Фактический результат:** тест не проходит, возвращается null

# Скриншот
![image](https://user-images.githubusercontent.com/121807872/227301542-c34a16c1-c7e5-4620-a259-186863bf55b8.png)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **JAVA:** OpenJDK 11

**Comment by OlgaMelman** [comment]
код исправлен, тест проходит
![one_hour](https://user-images.githubusercontent.com/107468964/228546876-0ddf3184-6a27-4597-9001-54e918e203bb.png)
