### ISSUE TITLE
Метод sumGenre не суммирует часы игры, проигранные игроком в конкретном жанре.

### ISSUE THREAD

**Issue by OlgaMelman** [Ntetikova/DiplomTeamWork_java#5]
# Описание
При суммировании времени, которое игрок потратил в играх одного жанра, метод выводит 0 часов.

# Локация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/218441b4a97fca34ba6ca33b76ab844715f6d7d0/src/main/java/ru/netology/Player.java#L53

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/gamestore/src/main/java/ru/netology/Player.java#L53) в IDEA
2. Запустить тест shouldSumGenreIfOneGame.
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Expected : 3
*Фактический результат:* Actual   : 0 

# Скриншот
![Screenshot_1 2png](https://user-images.githubusercontent.com/107468964/227715246-e83f69a5-5fc7-437f-b8b5-d4643501d832.png)

# Окружение
* **Операционная система:** Windows 11 21H2
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ntetikova** [comment]
![image](https://user-images.githubusercontent.com/121807872/228510702-020f0ad5-5207-455f-8953-059f92288dd9.png)
