### ISSUE TITLE
Нет возможности проверить обновление значений в мапе игрока.

### ISSUE THREAD

**Issue by OlgaMelman** [Ntetikova/DiplomTeamWork_java#6]
# Описание
Метод play должен добавлять часы, которые игрок проиграл в игру, обновляя тем самым мап.

# Локация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/218441b4a97fca34ba6ca33b76ab844715f6d7d0/src/main/java/ru/netology/Player.java#L12

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/gamestore/src/main/java/ru/netology/Player.java#L53) в IDEA
2. Запустить тест shouldUpdateTimeGame в PlayerTest.
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Expected : 3
*Фактический результат:* Actual   : java: playedTime has private access in ru.netology.Player

# Скриншот
![private](https://user-images.githubusercontent.com/107468964/227817859-4ced3eb0-5ca1-44d3-ade0-c28fd6f90a4a.png)

# Окружение
* **Операционная система:** Windows 11 21H2
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ntetikova** [comment]
Нет возможности проверить, так как данный тест закомментирован
![image](https://user-images.githubusercontent.com/121807872/228523937-397ff98b-913f-4109-b3b4-e9005870167d.png)
 Метод `play` "возвращает суммарное количество часов, проигранное в эту игру"
 
![image](https://user-images.githubusercontent.com/121807872/228524360-a027dc5a-bfcc-4f5d-8e86-a738bfd23416.png)
