### ISSUE TITLE
Метод mostPlayerByGenre не возвращает самую долго играемую в жанре игру.

### ISSUE THREAD

**Issue by OlgaMelman** [Ntetikova/DiplomTeamWork_java#7]
# Описание
При вызове метода mostPlayerByGenre программа не возвращает игру, в которую дольше всего играли в жанре.

# Локация дефекта
https://github.com/Ntetikova/DiplomTeamWork_java/blob/218441b4a97fca34ba6ca33b76ab844715f6d7d0/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/gamestore/src/main/java/ru/netology/Player.java#L53) в IDEA
2. Запустить тест shouldFindMostPlayerGameByGenre в PlayerTest.
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Expected : game2
*Фактический результат:* Actual   : null

# Скриншот
![Screenshot_4](https://user-images.githubusercontent.com/107468964/227716804-52d43629-adf0-4dba-bb00-7160236213e8.png)

# Окружение
* **Операционная система:** Windows 11 21H2
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ntetikova** [comment]
Метод поправлен, сам тест написан неверно. 
![image](https://user-images.githubusercontent.com/121807872/228518290-8ac3fd59-5b3d-4a0f-9a4f-0b711dd8a5d5.png)
**Необходимо поправить тест, тогда всё посчитает правильно.**
![image](https://user-images.githubusercontent.com/121807872/228518881-47b3774d-7549-49bc-a7da-79fab2a912fc.png)

**Comment by OlgaMelman** [comment]
исправила. тест проходит

# Скриншот 
![Screenshot_2](https://user-images.githubusercontent.com/107468964/228610913-192ce409-9a35-4d25-ac18-08be51a2ea63.png)
