### ISSUE TITLE
Отсутствует метод проверки метода installGame (добавление игры игроку)

### ISSUE THREAD

**Issue by OlgaMelman** [Ntetikova/DiplomTeamWork_java#8]
# Описание
Для проверки добавления игр игроку необходим отдельный метод, т.к. если игры не добавляются, то остальные методы будут работать некорректно.

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/gamestore/src/main/java/ru/netology/Player.java#L53) в IDEA

*Ожидаемый результат:* Expected : есть метод вывода добавленных игр игроку
*Фактический результат:* Actual   : нет метода

# Окружение
* **Операционная система:** Windows 11 21H2
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ntetikova** [comment]
Метод `installGame` добавлен
![image](https://user-images.githubusercontent.com/121807872/228513483-8ed05073-d076-41fe-a58f-0316d9bc9253.png)

**Comment by OlgaMelman** [comment]
Нужен отдельный метод по проверке добавления игры игроку.
Так как после коррекции метода installGame, я не могу сделать проверку на добавление одной и той же игры дважды.  true/false
