### ISSUE TITLE
Нет RuntimeException для неустановленной игры в методе play 

### ISSUE THREAD

**Issue by OlgaMelman** [Ntetikova/DiplomTeamWork_java#9]
# Описание
При вызове метода play программа должна выкидывать ошибку RuntimeException, если игра не установлена.

# Локация дефекта
нет кода

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ntetikova/DiplomTeamWork_java/blob/gamestore/src/main/java/ru/netology/Player.java#L53) в IDEA
2. Запустить тест shouldThrowException в PlayerTest.
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Expected : RuntimeException
*Фактический результат:* Actual   : nothing was thrown

# Скриншот
![exception](https://user-images.githubusercontent.com/107468964/227819689-c23c2b10-9e47-4765-9bef-3c0ab454f4d9.png)

# Окружение
* **Операционная система:** Windows 11 21H2
* **IDE:** IntelliJ IDEA 2022.1.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ntetikova** [comment]
![image](https://user-images.githubusercontent.com/121807872/228512232-de3d7175-57e5-448a-b0c8-2c1822759b03.png)
